name: CI/CD Pipeline - Spring Boot with Docker

on:
  push:
    branches: [ "update-optional" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "Chanwit21"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Create Git tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG
          git push https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/chanwit21/user-management-java-spring/user-management-app:latest
            ghcr.io/chanwit21/user-management-java-spring/user-management-app:${{ env.TAG }}
